### PR TITLE
Converted the  syba package into a .zip file and fetched it using wget

### PR DESCRIPTION
**Pull request by samuelmaina**
-Able to fetch from colab. [colab_eos7pw8_fetch (1).log](https://github.com/ersilia-os/eos7pw8/files/12035359/colab_eos7pw8_fetch.1.log)

### CODE REVIEW

**Comment by samuelmaina** [comment]
@GemmaTuron , I have made the changes. Can you have  look a look?

**Comment by GemmaTuron** [comment]
Hello @samuelmaina 

I see you are both downloading the package each time with the wget command and also adding it in the repository:
```
RUN wget https://github.com/samuelmaina/eos7pw8/raw/main/syba-master.zip
RUN unzip syba-master.zip && cd syba-master
RUN python setup.py install
RUN rm -rf syba-master.zip syba-master
```
If you add it in the repository, please delete the wget command. Also, the zip file is the model checkpoints, so place it in the correct place.
There is two copies of a legacy file (place_a_...) that must be deleted

**Comment by GemmaTuron** [comment]
That looks good, can you also delete the files place_a_docker... which I see duplicated twice in your fork, and then I'll merge the PR?

**Comment by samuelmaina** [comment]
Okay. I will remove it.

**Comment by samuelmaina** [comment]
Hi @GemmaTuron , test run successfully.

**Pull request merged**
